# metadata of the dataset

Metadata:
**STATE:**
State abbreviation (a nominal/symbolic field)
**PVASTATE**:
EPVA State or PVA State
Indicates whether the donor lives in a state served by the organization’s EPVA chapter
P = PVA State
E = EPVA State (Northeastern US)
**DOB:**
Date of birth (YYMM, Year/Month format.)
**RECP3**
P3 File Flag_ = Not a P3 Record
X = Donor has given to PVA’s P3 program
**MDMAUD**
The Major Donor Matrix code. The codes describe frequency and amount of
giving for donors who have given a $100+ gift at any time in their giving history. An RFA (recency/frequency/monetary) field. The (current) concatenated version is a nominal or symbolic field. The individual bytes could separately be used as fields and refer to the following:
First byte: Recency of Giving:
*  C=Current Donor
*  L=Lapsed Donor
*  I=Inactive Donor
*  D=Dormant Donor
2nd byte: Frequency of Giving:
*  1=One gift in the period of recency
*  2=Two-Four gifts in the period of recency
*  5=Five+ gifts in the period of recency
3rd byte: Amount of Giving:
*   L=Less than $100(Low Dollar)
*   C=$100-499(Core)
*   M=$500-999(Major)
*   T=$1,000+(Top)
4th byte: Blank/meaningless/filler:
**‘X’**
Indicates that the donor is not a major donor.
**‘GENDER’:**
Gender of the donor
**DOMAIN**
DOMAIN/Cluster code. A nominal or symbolic field.
could be broken down by bytes as explained below.
1st byte = Urbanicity level of the donor’s neighborhood
*   U=Urban
*   C=City
*   S=Suburban
*   T=Town
*   R=Rural
2nd byte = Socio-Economic status of the neighborhood
*   1 = Highest SES
*   2 = Average SES
*   3 = Lowest SES (except for Urban communities, where 1 = Highest SES,2 = Above average SES,3 = Below average SES, 4 = Lowest SES.)
**HOMEOWNR:** Home Owner Flag:
*   H = Home owner
*   U = Unknown
**‘INCOME’** HOUSEHOLD INCOME:
**HV1**  Median Home Value in hundreds.
**HV2** Average Home Value in hundreds.
**HV3**  Median Contract Rent in hundreds.
**HV4** Average Contract Rent in hundreds ‘IC1’.
**IC1**  Median Household Income in hundreds.
**IC2**  Median Family Income in hundreds.
**IC3**  Average Household Income in hundreds.
**IC4** Average Family Income in hundreds.
**IC5** Per Capita Income.
**‘VETERANS’**:
VETERANS (Y/N)
**‘RFA_2’**
Donor’s RFA status as of 97NK promotion date
**CARDPROM:**
Lifetime number of card promotions received to date. Card promotions are promotion type:
*   FS
*   GK
*   TK
*   SK
*   NK
*   XK
*   UF
*   UU
**MAXADATE:**
Date of the most recent promotion received (in YYMM, Year/Month format)
**NUMPROM:**
Lifetime number of promotions received to date
**CARDPM12:**
Number of card promotions received in the last 12 months (in terms of calendar months translates into 9603-9702)
**UMPRM12**
Number of promotions received in the last 12months (in terms of calendar months translates into 9603-9702)
**‘NGIFTALL’:**
Number of lifetime gifts to date.
**‘TIMELAG’:**
Number of months between first and second gift neighborhood demographics
**AGE901:**
Median Age of Population
**AGE902:**
Median Age of Adults 18 or Older
**AGE903:**
Median Age of Adults 25 or Older
**‘AVGGIFT’**
Average git amount

In [ ]:
# dependencies


import pandas as pd
import numpy as np
import datetime
import warnings

warnings.filterwarnings("ignore")


import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")

pd.options.display.max_columns =100

In [ ]:
# import the data

In [ ]:
data = pd.read_csv("HC4A_unit4_ver1.csv")
data

,STATE,PVASTATE,DOB,MDMAUD,RECP3,GENDER,DOMAIN,INCOME,HOMEOWNR,HV1,HV2,HV3,HV4,IC1,IC2,IC3,IC4,IC5,VETERANS,NUMPROM,CARDPROM,CARDPM12,NUMPRM12,MAXADATE,RFA_2,NGIFTALL,TIMELAG,AVGGIFT,TIMELAG_transformed
0,IL,NaN,3712,XXXX,NaN,F,T2,4.0,NaN,479,635,3,2,307,318,349,378,12883,NaN,74,27,6,14,9702,L4E,31,4.0,7.741935,1.386294
1,CA,NaN,5202,XXXX,NaN,M,S1,6.0,H,5468,5218,12,10,1088,1096,1026,1037,36175,NaN,32,12,6,13,9702,L2G,3,18.0,15.666667,2.890372
2,NC,NaN,0,XXXX,NaN,M,R2,3.0,U,497,546,2,1,251,292,292,340,11576,NaN,63,26,6,14,9702,L4E,27,12.0,7.481481,2.484907
3,CA,NaN,2801,XXXX,NaN,F,R2,1.0,U,1000,1263,2,1,386,388,396,423,15130,NaN,66,27,6,14,9702,L4E,16,9.0,6.812500,2.197225
4,FL,NaN,2001,XXXX,X,F,S2,3.0,H,576,594,4,3,240,250,293,321,9836,NaN,113,43,10,25,9702,L2F,37,14.0,6.864865,2.639057
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90564,FL,NaN,4803,XXXX,NaN,F,S2,6.0,H,733,875,4,3,285,288,333,334,11390,NaN,59,23,5,12,9702,L4D,24,3.0,3.375000,1.098612
90565,AK,NaN,0,XXXX,NaN,M,C2,4.0,NaN,988,1025,6,6,433,481,499,535,18807,NaN,14,6,5,12,9702,L1G,1,NaN,25.000000,1.826874
90566,TX,NaN,5001,XXXX,NaN,M,C1,7.0,H,1679,1723,3,3,806,836,802,849,26538,NaN,10,4,3,8,9702,L1F,1,NaN,20.000000,1.826874
90567,MI,NaN,3801,XXXX,X,M,C3,3.0,NaN,376,377,4,3,263,264,319,345,12178,NaN,33,14,7,17,9702,L3E,7,3.0,8.285714,1.098612
90568,NC,NaN,1801,C1CM,NaN,F,C1,5.0,U,938,1049,5,5,451,474,499,519,16699,NaN,139,32,6,35,9702,L1G,39,6.0,96.794872,1.791759

In [ ]:
data.shape

(90569, 29)

In [ ]:
# checking data types

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90569 entries, 0 to 90568
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   STATE                90569 non-null  object
 1   PVASTATE             1385 non-null   object
 2   DOB                  90569 non-null  int64
 3   MDMAUD               90569 non-null  object
 4   RECP3                1833 non-null   object
 5   GENDER               87774 non-null  object
 6   DOMAIN               88393 non-null  object
 7   INCOME               90569 non-null  float64
 8   HOMEOWNR             69518 non-null  object
 9   HV1                  90569 non-null  int64
 10  HV2                  90569 non-null  int64
 11  HV3                  90569 non-null  int64
 12  HV4                  90569 non-null  int64
 13  IC1                  90569 non-null  int64
 14  IC2                  90569 non-null  int64
 15  IC3                  90569 non-null  int64
 16  IC4                  90569 non-null  int64
 17  IC5                  90569 non-null  int64
 18  VETERANS             9846 non-null   object
 19  NUMPROM              90569 non-null  int64
 20  CARDPROM             90569 non-null  int64
 21  CARDPM12             90569 non-null  int64
 22  NUMPRM12             90569 non-null  int64
 23  MAXADATE             90569 non-null  int64
 24  RFA_2                90569 non-null  object
 25  NGIFTALL             90569 non-null  int64
 26  TIMELAG              80916 non-null  float64
 27  AVGGIFT              90569 non-null  float64
 28  TIMELAG_transformed  90569 non-null  float64
dtypes: float64(4), int64(16), object(9)
memory usage: 20.0+ MB

In [ ]:
data.isna().sum()/len(data)

STATE                  0.000000
PVASTATE               0.984708
DOB                    0.000000
MDMAUD                 0.000000
RECP3                  0.979761
GENDER                 0.030860
DOMAIN                 0.024026
INCOME                 0.000000
HOMEOWNR               0.232431
HV1                    0.000000
HV2                    0.000000
HV3                    0.000000
HV4                    0.000000
IC1                    0.000000
IC2                    0.000000
IC3                    0.000000
IC4                    0.000000
IC5                    0.000000
VETERANS               0.891287
NUMPROM                0.000000
CARDPROM               0.000000
CARDPM12               0.000000
NUMPRM12               0.000000
MAXADATE               0.000000
RFA_2                  0.000000
NGIFTALL               0.000000
TIMELAG                0.106582
AVGGIFT                0.000000
TIMELAG_transformed    0.000000
dtype: float64

In [ ]:
# check categorical columns

In [ ]:
categoricals = data.select_dtypes(object)
categoricals

      STATE PVASTATE MDMAUD RECP3 GENDER DOMAIN HOMEOWNR VETERANS RFA_2
0        IL      NaN   XXXX   NaN      F     T2      NaN      NaN   L4E
1        CA      NaN   XXXX   NaN      M     S1        H      NaN   L2G
2        NC      NaN   XXXX   NaN      M     R2        U      NaN   L4E
3        CA      NaN   XXXX   NaN      F     R2        U      NaN   L4E
4        FL      NaN   XXXX     X      F     S2        H      NaN   L2F
...     ...      ...    ...   ...    ...    ...      ...      ...   ...
90564    FL      NaN   XXXX   NaN      F     S2        H      NaN   L4D
90565    AK      NaN   XXXX   NaN      M     C2      NaN      NaN   L1G
90566    TX      NaN   XXXX   NaN      M     C1        H      NaN   L1F
90567    MI      NaN   XXXX     X      M     C3      NaN      NaN   L3E
90568    NC      NaN   C1CM   NaN      F     C1        U      NaN   L1G

[90569 rows x 9 columns]

In [ ]:
# delete columns with 80% empty values

In [ ]:
data = data.drop(columns=["PVASTATE", "RECP3", "VETERANS"], axis=1)

In [ ]:
data.columns

Index(['STATE', 'DOB', 'MDMAUD', 'GENDER', 'DOMAIN', 'INCOME', 'HOMEOWNR',
       'HV1', 'HV2', 'HV3', 'HV4', 'IC1', 'IC2', 'IC3', 'IC4', 'IC5',
       'NUMPROM', 'CARDPROM', 'CARDPM12', 'NUMPRM12', 'MAXADATE', 'RFA_2',
       'NGIFTALL', 'TIMELAG', 'AVGGIFT', 'TIMELAG_transformed'],
      dtype='object')

In [ ]:
# inspection of single column HOMEOWN
data['HOMEOWNR'].value_counts(dropna=False)/len(data)

H      0.548157
NaN    0.232431
U      0.219413
Name: HOMEOWNR, dtype: float64

In [ ]:
# delete the column

# the amount of nans with U label amount to 44% which is highly uncertain
# any method here will introduce lot bias (where you data analysts need to convince us)

data = data.drop(columns="HOMEOWNR", axis=1)

In [ ]:
# clean GENDER
data.GENDER.value_counts()

F    48668
M    37132
U     1635
J      336
C        2
A        1
Name: GENDER, dtype: int64

In [ ]:
def clean_gender_col(x):
    if x in ["U", "J", "C", "A"]:
        return "non_binary"
    else:
        return x
    
data["GENDER"] = data["GENDER"].apply(clean_gender_col) # clean_gender_col(data["GENDER"])
data["GENDER"] = data["GENDER"].apply( lambda x: clean_gender_col(x))

In [ ]:
data["GENDER"].value_counts()

F             48668
M             37132
non_binary     1974
Name: GENDER, dtype: int64

In [ ]:
# CODE ISRA TO REVIEW (MAP)

#map = {'U' : 'Nonbinary', 'J' : 'Nonbinary', 'C' : 'Nonbinary', 'A': 'Nonbinary', 'F' : 'F', 'M' : 'M'}

#df['GENDER'].map(map) = df['GENDER'].map(map)

In [ ]:
# columns DOMAIN

In [ ]:
# VISUALIZE CATEGORICAL VARIABLES VS TARGET
sns.catplot(x=df['GENDER'], y=df['AVGGIFT'], data=df)

NameError: ignored

In [ ]:
# transformations on the numerical variables

In [ ]:
# dealing with STATE VARIABLE

In [ ]:
# grouping data

In [ ]:
# regular expressions

In [ ]:
# Select the first quantile
q1 = df['AVGGIFT'].quantile(.25)

# Select the third quantile
q3 = df['AVGGIFT'].quantile(.75)

# Create a mask inbeetween q1 & q3
mask = df['AVGGIFT'].between(q1, q3, inclusive=True)

# Filtering the initial dataframe with a mask
iqr = df.loc[mask, 'AVGGIFT']

In [ ]:
# The column customer should be set it as the index.
customer_df.set_index("customer", inplace = True)
display(customer_df)

In [ ]:
for x in ["F", "M", "non_binary"]:
    # Select the first quantile
    q1 = data['AVGGIFT'][data.GENDER == x].quantile(.25)
    # Select the third quantile
    q3 = data['AVGGIFT'][data.GENDER == x].quantile(.75)
    # Create a mask inbeetween q1 & q3
    data['AVGGIFT'][data.GENDER == x].between((q1-1.5*(q3-q1)), (q3 + 1.5*(q3-q1)), inclusive=True)